# Paperweight
group = me.sosedik.kiterino
version = 1.21.1-R0.1-SNAPSHOT
mcVersion = 1.21.1

# Upstream commit
purpurCommit = d49ca07e0098cd9e923d43b7fe67fb7e2a8eb511

# Gradle
org.gradle.caching = true
org.gradle.parallel = true
org.gradle.vfs.watch = false
org.gradle.jvmargs = -Xmx3G
