# Paperweight
group = me.sosedik.kiterino
version = 1.21.4-R0.1-SNAPSHOT
mcVersion = 1.21.4

# Upstream commit
purpurCommit = a9bcd9f0c8b66ad84f9ca6005d425902c9cd0442

# Gradle
org.gradle.configuration-cache=true
org.gradle.caching = true
org.gradle.parallel = true
org.gradle.vfs.watch = false
