# Paperweight
group = me.sosedik.kiterino
version = 1.21.1-R0.1-SNAPSHOT
mcVersion = 1.21.1

# Upstream commit
purpurCommit = d7a7c91a7fd28d77980ce3da06bdf69e8fef92af

# Gradle
org.gradle.caching = true
org.gradle.parallel = true
org.gradle.vfs.watch = false
org.gradle.jvmargs = -Xmx3G
